#!/usr/bin/env bash
# yaml-framework adapter — Converts SKILL.md to YAML-wrapped format
# Usage: yaml-framework.sh <source_skill_md> <target_directory>

set -euo pipefail

SOURCE="$1"
TARGET="$2"

mkdir -p "$TARGET"

# Read SKILL.md content
CONTENT=$(cat "$SOURCE")

# Generate YAML wrapper
cat > "$TARGET/skill.yaml" <<HEREDOC
# Auto-generated by skill-hub yaml-framework adapter
# Source: $SOURCE

$(echo "$CONTENT" | sed 's/^/  /')
HEREDOC

echo "  ✅ Generated $TARGET/skill.yaml"
